// EPISODE 4 — "Kunci yang Cocok"
export default {
  id: 'ep04',
  no: 4,
  title: 'Kunci yang Cocok',
  judulUpload: 'Kunci misterius di tasnya membuka gudang 10 tahun 🔑 #4',
  bgm: 'audio/bgm/ep04.mp3',
  shots: [
    {
      d: 2.2, beat: 'hook', loc: 'kelas', fx: ['zoom'],
      cam: { s: 'insert', point: [-1.1, 0.78, 0.05], off: [0.15, 0.3, 0.45], m: 'push', amt: 1.5 },
      cast: { hana: { at: 'bangku', face: 180, anim: 'sit', expr: 'neutral' } },
      props: [{ p: 'key', at: [-1.1, 0.78, 0.05] }],
      hook: 'KUNCI MISTERIUS DI TASKU',
    },
    {
      d: 3.8, beat: 'konflik', loc: 'kelas',
      cam: { s: 'medium', on: 'mira', m: 'push' },
      cast: {
        mira: { at: 'A', face: 'hana', anim: 'grab', expr: 'smirk' },
        hana: { at: 'bangku', face: 'mira', anim: 'sit', expr: 'scared' },
        riko: { at: 'B', face: 'hana', anim: 'laugh', expr: 'happy' },
      },
      props: [{ p: 'bag', at: [-0.5, 1.1, 0.25] }],
      lines: [{ who: 'mira', text: 'Coba lihat isi tas orang miskin.', note: 'mengejek, lantang' }],
    },
    {
      d: 3.4, loc: 'kelas', fx: ['shake'],
      cam: { s: 'insert', point: [-0.7, 0.05, 0.4], off: [0.3, 0.6, 0.8], m: 'tilt' },
      cast: { mira: { at: 'A', face: 'hana', anim: 'holdup', expr: 'smirk' } },
      props: [
        { p: 'papers', at: [-0.7, 0.01, 0.4] },
        { p: 'key', at: [-0.6, 1.0, 0.35], to: [-0.7, 0.03, 0.55], spin: true },
      ],
      pop: 'KLONTANG!',
      caption: 'Sebuah kunci tua jatuh',
      sfx: [{ src: 'audio/sfx/logam-jatuh.mp3', at: 0.6 }],
    },
    {
      d: 3.6, loc: 'kelas',
      cam: { s: 'close', on: 'riko', m: 'handheld' },
      cast: { riko: { at: 'B', face: 'hana', anim: 'laugh', expr: 'happy' }, hana: { at: 'bangku', face: 'riko', anim: 'sit', expr: 'sad' } },
      lines: [{ who: 'riko', text: 'Kunci karatan? Rumahmu gudang, ya?', note: 'tertawa' }],
    },
    {
      d: 3.8, loc: 'kelas',
      cam: { s: 'close', on: 'hana', m: 'push' },
      cast: { hana: { at: [-0.75, 0.6], face: 30, anim: 'pickup', expr: 'think' } },
      props: [{ p: 'key', at: [-0.7, 0.03, 0.55] }],
      lines: [{ who: 'hana', text: 'Kunci ini... bukan punyaku.', note: 'bingung, pelan' }],
    },
    {
      d: 4.2, loc: 'kelas', fx: ['sepia', 'vignette'],
      cam: { s: 'insert', point: [-0.75, 1.0, 0.85], off: [0, 0.05, 0.35], m: 'orbit' },
      cast: { hana: { at: [-0.75, 0.6], face: 0, anim: 'idle', expr: 'think' } },
      props: [{ p: 'key', at: [-0.75, 1.0, 0.85], spin: true }],
      caption: 'Pesan Nenek Sumi, tadi pagi',
      lines: [{ who: 'sumi', vo: true, text: 'Simpan ini. Suatu hari kamu mengerti.', note: 'suara nenek, hangat, bergema' }],
    },
    {
      d: 4.2, beat: 'eskalasi', loc: 'gudang_luar',
      cam: { s: 'wide', angle: 160, m: 'push', dist: 5 },
      cast: { hana: { at: 'C', to: 'A', face: 180, anim: 'walk', expr: 'think' } },
      caption: 'Sepulang sekolah...',
      lines: [{ who: 'hana', text: 'Gudang Klub Musik... terkunci sepuluh tahun?', note: 'membaca papan' }],
    },
    {
      d: 3.6, loc: 'gudang_luar',
      cam: { s: 'medium', on: 'sae', m: 'pan' },
      cast: {
        sae: { at: 'B', face: 'hana', anim: 'point', expr: 'surprised' },
        hana: { at: 'A', face: 'sae', anim: 'surprised', expr: 'surprised' },
      },
      lines: [{ who: 'sae', text: 'Hana! Tempat itu sudah lama ditutup.', note: 'agak panik' }],
    },
    {
      d: 4.4, loc: 'gudang_luar',
      cam: { s: 'ots', on: 'sae', from: 'hana', m: 'push' },
      cast: {
        sae: { at: 'B', face: 'hana', anim: 'sad', expr: 'sad' },
        hana: { at: 'A', face: 'sae', anim: 'idle', expr: 'think' },
      },
      lines: [
        { who: 'hana', text: 'Kenapa ditutup, Bu?' },
        { who: 'sae', text: 'Ada kejadian... dulu sekali.', note: 'mengalihkan pandangan' },
      ],
    },
    {
      d: 3.2, loc: 'gudang_luar',
      cam: { s: 'close', on: 'sae', m: 'pull' },
      cast: { sae: { at: 'B', to: 'C', face: 150, anim: 'walk', expr: 'sad', move: [0.3, 1] } },
      lines: [{ who: 'sae', text: 'Pulanglah sebelum gelap.', note: 'pelan, sedih' }],
    },
    {
      d: 3.6, beat: 'twist', loc: 'gudang_luar', fx: ['flash', 'zoom'],
      cam: { s: 'insert', point: [0.25, 1.0, -1.72], off: [0.05, 0.08, 0.35], m: 'push', amt: 1.5 },
      cast: { hana: { at: 'pintu', face: 180, anim: 'unlock', expr: 'think' } },
      props: [{ p: 'padlock', at: [0.25, 1.0, -1.72] }, { p: 'key', at: [0.25, 1.0, -1.66] }],
      pop: 'KLIK!',
      caption: 'Kuncinya... cocok.',
      sfx: [{ src: 'audio/sfx/klik.mp3', at: 1.2 }],
    },
    {
      d: 3.6, loc: 'gudang_luar', fx: ['vignette'],
      cam: { s: 'xclose', on: 'hana', angle: 20, m: 'push' },
      cast: { hana: { at: 'pintu', face: 20, anim: 'surprised', expr: 'surprised' } },
      lines: [{ who: 'hana', text: 'Tidak mungkin... cocok?!', note: 'terkejut, berbisik' }],
    },
    {
      d: 3.8, loc: 'gudang_luar', fx: ['dust'],
      cam: { s: 'wide', angle: 180, dist: 4, m: 'push', amt: 1.3 },
      door: 'opening',
      cast: { hana: { at: 'A', face: 180, anim: 'scared', expr: 'scared' } },
      hook: 'GUDANG 10 TAHUN TERBUKA',
      sfx: [{ src: 'audio/sfx/pintu-berderit.mp3', at: 0.2 }],
    },
    {
      d: 3.8, beat: 'cliff', end: true, loc: 'gudang_luar', fx: ['vignette'],
      door: 'open',
      cam: { s: 'medium', on: 'mira', m: 'push' },
      cast: {
        mira: { at: 'pohon', face: 'hana', anim: 'crossarms', expr: 'smirk' },
        hana: { at: 'A', face: 180, anim: 'idle', expr: 'scared' },
      },
      caption: 'Seseorang mengawasi dari balik pohon',
      lines: [{ who: 'mira', text: 'Menarik sekali, Aozora.', note: 'berbisik, licik' }],
    },
  ],
};
