// EPISODE 5 — "Piano dan Foto Ibu"
export default {
  id: 'ep05',
  no: 5,
  title: 'Piano dan Foto Ibu',
  judulUpload: 'Di gudang terkunci, dia menemukan foto ibunya 😳 #5',
  bgm: 'audio/bgm/ep05.mp3',
  shots: [
    {
      d: 2.2, beat: 'hook', loc: 'gudang_dalam', fx: ['dust'],
      cam: { s: 'wide', angle: 0, m: 'push', amt: 1.5 },
      cover: 'on',
      cast: { hana: { at: 'pintu', to: [0, 2.2], face: 180, anim: 'walk', expr: 'scared' } },
      hook: 'APA YANG DISEMBUNYIKAN GUDANG INI?',
    },
    {
      d: 3.8, beat: 'konflik', loc: 'gudang_dalam', fx: ['dust'],
      cam: { s: 'medium', on: 'hana', m: 'handheld' },
      cover: 'on',
      cast: { hana: { at: [0, 2.2], to: 'A', face: 180, anim: 'phone', expr: 'scared', flashlight: true } },
      lines: [{ who: 'hana', text: 'Halo...? Ada orang di sini?', note: 'takut, bergema' }],
      sfx: [{ src: 'audio/sfx/tetesan-air.mp3', at: 0.5 }],
    },
    {
      d: 3.4, loc: 'gudang_dalam', fx: ['dust'],
      cam: { s: 'insert', point: [0, 0.9, -1.1], off: [1.4, 0.5, 1.3], m: 'pan' },
      cover: 'on',
      cast: { hana: { at: 'A', face: 180, anim: 'lookaround', expr: 'scared', flashlight: true } },
      caption: 'Semua tertutup kain putih',
    },
    {
      d: 3.6, loc: 'gudang_dalam', fx: ['dust', 'shake'],
      cam: { s: 'medium', on: 'hana', angle: 40, m: 'push' },
      cover: 'removing',
      cast: { hana: { at: [0, -0.35], face: 180, anim: 'pull', expr: 'think' } },
      pop: 'SRAAK!',
      sfx: [{ src: 'audio/sfx/kain.mp3', at: 0.4 }],
    },
    {
      d: 4.0, beat: 'eskalasi', loc: 'gudang_dalam',
      cam: { s: 'close', on: 'hana', angle: 30, m: 'orbit' },
      cover: 'off',
      cast: { hana: { at: [0, -0.35], face: 180, anim: 'idle', expr: 'surprised' } },
      lines: [{ who: 'hana', text: 'Masih berbunyi... setelah sepuluh tahun?', note: 'takjub, setelah nada piano' }],
      sfx: [{ src: 'audio/sfx/piano-nada.mp3', at: 0 }],
    },
    {
      d: 3.6, loc: 'gudang_dalam', fx: ['zoom'],
      cam: { s: 'insert', point: [0.45, 1.25, -1.25], off: [0, 0.02, 0.45], m: 'push', amt: 1.5 },
      cover: 'off',
      cast: { hana: { at: [0, -0.35], face: 180, anim: 'idle', expr: 'surprised' } },
      caption: 'Sebuah foto lama di atas piano',
    },
    {
      d: 3.8, loc: 'gudang_dalam', fx: ['vignette'],
      cam: { s: 'xclose', on: 'hana', angle: 20, m: 'push' },
      cover: 'off',
      cast: { hana: { at: [0, -0.35], face: 160, anim: 'surprised', expr: 'surprised' } },
      lines: [{ who: 'hana', text: 'Pita biru ini... Ibu?', note: 'napas tertahan' }],
    },
    {
      d: 4.6, loc: 'gudang_dalam', fx: ['sepia', 'vignette', 'dust'],
      cam: { s: 'medium', on: 'aoi', angle: 35, m: 'orbit' },
      cover: 'off', mood: 'dalam',
      cast: { aoi: { at: 'kursi', face: 180, anim: 'piano', expr: 'smile' } },
      caption: '10 tahun lalu...',
      lines: [{ who: 'aoi', text: 'Bernyanyilah, Hana. Jangan pernah takut.', note: 'lembut, hangat (kenangan)' }],
      sfx: [{ src: 'audio/sfx/piano-melodi.mp3', at: 0 }],
    },
    {
      d: 4.2, loc: 'gudang_dalam', fx: ['dust'],
      cam: { s: 'close', on: 'hana', angle: 45, m: 'orbit' },
      cover: 'off',
      cast: { hana: { at: 'kursi', face: 180, anim: 'piano', expr: 'sad' } },
      caption: '(Hana bernyanyi pelan)',
      lines: [{ who: 'hana', text: '♪ Bunga kecil di balik kaca... ♪', note: 'bernyanyi lirih — melodi orisinal' }],
    },
    {
      d: 3.4, loc: 'gudang_dalam', fx: ['vignette'],
      cam: { s: 'xclose', on: 'hana', angle: 30, m: 'push' },
      cover: 'off',
      cast: { hana: { at: 'kursi', face: 180, anim: 'piano', expr: 'cry' } },
      caption: 'Suara yang ia sembunyikan selama ini',
    },
    {
      d: 4.2, beat: 'twist', loc: 'gudang_dalam', fx: ['flash', 'shake'],
      cam: { s: 'ots', on: 'ren', from: 'hana', m: 'push', amt: 1.3 },
      cover: 'off',
      cast: {
        hana: { at: 'kursi', face: 'ren', anim: 'sit', expr: 'scared' },
        ren: { at: 'pintu', face: 180, anim: 'idle', expr: 'cold', silhouette: true },
      },
      pop: 'KRIIIT...',
      hook: 'ADA YANG MENDENGAR!',
      sfx: [{ src: 'audio/sfx/pintu-berderit.mp3', at: 0 }],
    },
    {
      d: 3.6, loc: 'gudang_dalam',
      cam: { s: 'close', on: 'hana', angle: -30, m: 'handheld' },
      cover: 'off',
      cast: { hana: { at: 'kursi', face: 0, anim: 'scared', expr: 'scared' } },
      lines: [{ who: 'hana', text: 'S-siapa di sana?!', note: 'ketakutan' }],
    },
    {
      d: 3.8, loc: 'gudang_dalam', fx: ['dust'],
      cam: { s: 'low', on: 'ren', m: 'push' },
      cover: 'off',
      cast: { ren: { at: 'pintu', to: [0, 2.2], face: 180, anim: 'walk', expr: 'cold', silhouette: true } },
      caption: 'Langkah kaki mendekat...',
      sfx: [{ src: 'audio/sfx/langkah.mp3', at: 0 }],
    },
    {
      d: 3.2, beat: 'cliff', end: true, loc: 'gudang_dalam', fx: ['vignette'],
      cam: { s: 'close', on: 'ren', m: 'push', amt: 1.4 },
      cover: 'off',
      cast: { ren: { at: [0, 2.2], face: 180, anim: 'idle', expr: 'cold', silhouette: true } },
      lines: [{ who: 'ren', hideName: true, text: 'Suara itu... aku kenal.', note: 'pelan (identitas masih dirahasiakan)' }],
    },
  ],
};
